spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/proddb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: produser
    password: prodpassword
  jpa:
    hibernate:
      ddl-auto: validate